-- Closes a tenant-isolation gap in two tables that have been unprotected since
-- 0015_special_barracuda.sql created them.
--
-- `doctor_slot_overrides` and `doctor_interval_blocks` both carry hospital_id
-- and cascade from hospitals, but no migration ever enabled row-level security
-- on them: 0015 was generated by drizzle-kit, and the hand-written policy step
-- that 0001 applies to every other tenant table was never added alongside it.
--
-- This mattered because the queries that read them filter on doctor_id alone
-- (see getDoctorSlotsForDate in lib/services/scheduling.ts). On every other
-- table a missing hospital filter is a no-rows bug; on these two it was a
-- cross-tenant read. Nothing is known to have exploited it — every caller goes
-- through withTenant() and sets hospital_id on insert, which is also why
-- enabling the policies now cannot break them.
--
-- Found by the "leaves no tenant table outside row-level security" case in
-- lib/db/__tests__/rls.integration.test.ts, which asserts the set of
-- unprotected tables is empty rather than listing the protected ones, so the
-- next table to miss this fails a test instead of shipping.
DO $outer$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'doctor_slot_overrides',
    'doctor_interval_blocks'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);

    -- Guarded so this migration is safe to re-run against a database where the
    -- policies were added by hand before it shipped.
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = t AND policyname = 'tenant_isolation'
    ) THEN
      EXECUTE format(
        $p$
          CREATE POLICY tenant_isolation ON %I
            USING (hospital_id = nullif(current_setting('app.hospital_id', true), '')::uuid)
            WITH CHECK (hospital_id = nullif(current_setting('app.hospital_id', true), '')::uuid)
        $p$,
        t
      );
    END IF;

    -- The same read-only guard 0023 gives every other tenant table, so a
    -- support session cannot quietly rewrite a doctor's availability.
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = t AND policyname = 'read_only_write'
    ) THEN
      EXECUTE format(
        $p$
          CREATE POLICY read_only_write ON %I AS RESTRICTIVE
            FOR ALL
            USING (true)
            WITH CHECK (NOT public.app_read_only())
        $p$,
        t
      );
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = t AND policyname = 'read_only_delete'
    ) THEN
      EXECUTE format(
        $p$
          CREATE POLICY read_only_delete ON %I AS RESTRICTIVE
            FOR DELETE
            USING (NOT public.app_read_only())
        $p$,
        t
      );
    END IF;
  END LOOP;
END
$outer$;
